wan1_interface: "wan1"
wan2_interface: "wan2"
loopback_interface: "loopback0"
lan_interface: "lan"

wan1_ip: "192.168.100.2/30"
wan2_ip: "192.168.200.2/30"
loopback_ip: "1.1.1.1/32"
lan_ip: "192.168.1.1/24"

wan1_gateway: "192.168.100.1"
wan2_gateway: "192.168.200.1"

primary_dns: "208.91.112.51"
secondary_dns: "208.91.112.52"

advpn_main: "ADVPN_MAIN"
local_gw_advpn_main: "192.168.100.2"
advpn_main_startip: "169.254.10.1"
advpn_main_endip: "169.254.10.250"
psksecret_main: "L1nt4s4rt@"

advpn_backup: "ADVPN_BACKUP"
local_gw_advpn_backup: "192.168.200.2"
advpn_backup_startip: "169.254.20.1"
advpn_backup_endip: "169.254.20.250"
psksecret_backup: "L1nt4s4rt@"
